name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
        
    - name: Push to Hugging Face Spaces
      env:
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME
        git push hf main:main --force